name = "Dendrite"
uuid = "66ec3854-9b2e-4ee8-8796-135b58891944"
authors = ["arhik <arhik23@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
